config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :customers, only: [:index, :show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

require_relative '../services/order_service'

class Customer
  include ActiveModel::Model

  attr_accessor :id,
                :company,
                :first_name,
                :last_name,
                :email,
                :phone,
                :form_fields,
                :date_created,
                :date_modified,
                :store_credit,
                :registration_ip_address,
                :customer_group_id,
                :notes,
                :tax_exempt_category,
                :reset_pass_on_login,
                :accepts_marketing


  def full_name
    "#{first_name} #{last_name}"
  end

  def orders
    order_service.orders_list
  end

  def orders_count
    order_service.orders_count
  end

  private

  def order_service
    @order_service ||= OrderService.new(params: {customer_id: id})
  end
end

app/models/order.rb
# frozen_string_literal: true

require_relative '../services/order_service'

class Order
  include ActiveModel::Model

  attr_accessor :id,
                :customer_id,
                :date_created,
                :date_modified,
                :date_shipped,
                :status,
                :subtotal_inc_tax,
                :shipping_cost_inc_tax,
                :handling_cost_inc_tax,
                :wrapping_cost_inc_tax,
                :total_inc_tax,
                :total_tax,
                :items_total,
                :items_shipped,
                :payment_method,
                :payment_status,
                :refunded_amount,
                :customer_message,
                :products,
                :custom_status

  def product_count
    order_service.order_products_count
  end

  private

  def order_service
    @order_service ||= OrderService.new(
        params: {customer_id: customer_id, order_id: id}
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

require_relative '../services/customer_service'

class CustomersController < ApplicationController

  def index
    @customers = CustomerService.new(params: {}).customers_list
  end

  def show
    @customer = CustomerService.new(
        params: {customer_id: params[:id]}
    ).customer
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  ##
  # Confirms that the API Client is configured correctly.
  def index
    time_response = Bigcommerce::System.time
    @time = time_response.respond_to?(:time) ? Time.at(time_response.time).strftime('%H:%M:%S') : 'N/A'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.erb
<% content_for :title, 'Customers' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Store Credit</th>
      <th># of Orders</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.full_name, customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.store_credit %></td>
        <td><%= customer.orders_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/show.html.erb
<% content_for :title, "#{@customer.full_name}'s Order History" %>

<table>
  <thead>
    <tr>
      <th>Order Date</th>
      <th>Shipping Date</th>
      <th>Status</th>
      <th>Payment Method</th>
      <th>Payment Status</th>
      <th># of Products</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% lifetime_value = 0.0 %>
    <% @customer.orders.each do |order| %>
      <tr>
        <td><%= order.date_created %></td>
        <td><%= order.date_shipped %></td>
        <td><%= order.status %></td>
        <td><%= order.payment_method %></td>
        <td><%= order.payment_status %></td>
        <td><%= order.product_count %></td>
        <td><%= number_to_currency(order.total_inc_tax) %></td>
        <td><% lifetime_value +=  order.total_inc_tax&.to_f %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="2"><strong>Lifetime Value</strong></td>
      <td><strong><%= number_to_currency(lifetime_value) %></strong></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= yield(:title) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>
      <img class="title-area-logo" src="https://wwwcdn.bigcommerce.com/www1.bigcommerce.com/assets/logos/bc-logo-dark.svg" alt="">
      <%= yield(:title) %>
    </h1>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.erb
<% content_for :title,  'Candidate Assignment' %>

<h3><%= @time %></h3>

<nav>
  <ul>
    <li>
      <a href="/customers">Customers</a>
    </li>
  </ul>
</nav>